image: archlinux
packages:
  - rustup
sources:
  - "https://github.com/laxect/diva-livomo.git"
tasks:
  - setup: |
      rustup default stable
  - build: |
      cd diva-livomo
      cargo build --release
artifacts:
  - "diva-livomo/target/release/dival"
